// Embeds the atc-bridge mod's files into a generated module under src/, so
// the daemon can write the mod from a compiled binary. The atc command the
// mod runs is rendered when the daemon writes it, and the mod's tests stay
// behind.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

function main(): void {
  const modDir = join(import.meta.dir, '..', 'mods', 'atc-bridge');
  const embedded = ['.claude-plugin/plugin.json', 'hooks/hooks.json', 'hooks/register.ts'];

  const entries = embedded.map(
    (path) => `  '${path}': ${JSON.stringify(readFileSync(join(modDir, path), 'utf8'))},`,
  );

  writeFileSync(
    join(import.meta.dir, '..', 'src', 'agents', 'atc-bridge-files.ts'),
    [
      '// Generated by `bun run build:atc-bridge` from mods/atc-bridge; edit the mod, then rerun it.',
      '// oxlint-disable no-template-curly-in-string -- the strings are the mod source, template literals included',
      `export const ATC_BRIDGE_FILES: Readonly<Record<${embedded.map((path) => `'${path}'`).join(' | ')}, string>> = {`,
      ...entries,
      '};',
      '',
    ].join('\n'),
  );
}

main();
